
apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: postapp
spec:
spec:
  selector:
    app: post-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
